
variables:
  REGISTRY: $CI_REGISTRY_IMAGE
  APP: mbot

stages:
  - ci
  - cd
  
build:
  image: docker:latest
  services:
    - docker:dind
  stage: ci
  before_script:
    - apk  update && apk add make
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - make image push


update_version:
  image: golang:latest
  stage: cd
  before_script:
    - go install github.com/mikefarah/yq/v4@latest
  script:
    - git config --global user.email "gitlab-bot@example.com"
    - git config --global user.mame "Gitlab Bot"
    - echo "VERSION=$(git describe --tags --abbrev=0)-$(git rev-parse --short HEAD)"
    - yq -i '.image.tag=strenv(VERSION)' helm/values.yaml
    - git checkout develop
    - git commit -am "Update version $VERSION"
    - git remote set-url origin https://oauth2:${CI_BOT_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git
    - git push -o ci.skip  develop
