image: golang:latest

variables:
  REGISTRY: $CI_REGISTRY_IMAGE
  APP: mbot

stages:
  - build
  
build:
  image: docker:latest
  services:
    - docker:dind
  stage: build
  before_script:
    - apk  update && apk add make
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - make image push
