image: golang:latest

variables:
  REGISTRY: $CI_REGISTRY_IMAGE

stages:
  - build
  - deploy
 

build:
  stage: build
  script :
    - go build

deploy:
  image: docker:latest
  services:
    - docker:dind
  stage: deploy
  before_script:
    - apt install update && apt install make
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - make image push
