
variables:
  REGISTRY: $CI_REGISTRY_IMAGE
  APP: mbot

stages:
  - ci
  - cd
  
build:
  image: docker:latest
  services:
    - docker:dind
  stage: ci
  before_script:
    - apk  update && apk add make
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - make image push


update_version:
  image: golang:latest
  stage: cd
  before_script:
    - go install github.com/mikefarah/yq/v4@latest
    - git clone -b develop  "https://${CI_BOT_NAME}:${CI_BOT_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git" "${CI_COMMIT_SHA}"
    - cd ${CI_COMMIT_SHA}
    - git status
    # Set the displayed user with the commits that are about to be made
    - git config --global user.email "${CI_BOT_NAME}@dev.nul"
    - git config --global user.name "${CI_BOT_NAME}"

  script:
    - echo "VERSION=$(git describe --tags --abbrev=0)-$(git rev-parse --short HEAD)"
    - yq -i '.image.tag=strenv(VERSION)' helm/values.yaml
    - git checkout develop
    - git commit -am "Update version $VERSION"
    - git push -o ci.skip  develop
