name: MBOT_CICD
on: push

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: GitHub Registry Login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.USER_NAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build&Push
        env:
          APP: "mbot"
          REGISTRY: ${{ secrets.GH_REGISTRY_NAME }}
        run: |
          make image push


 
